server:
  servlet:
    context-path: /api
spring:
  application:
    name: 'Code Annotation Server'
  profiles:
    active:
      - ${ENV:local}
      - openapi
      - management
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        jdbc:
          batch_size: 50
  mvc:
    resources:
      add-mappings: false
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: classpath:/db/migrations.yaml

org.jobrunr:
  database:
    # Need to import schema of JobRunR tables via schema.sql due to a bug of JobRunR
    # that is failed to run migration to initialize its tables.
    skip-create: true
  dashboard.enabled: true
  background-job-server:
    enabled: true
    worker-count: 2

app:
  auth:
    public-endpoints:
      - /actuator/prometheus
      - /v1/auth/token
      - /v1/auth/refresh-token
      - /v1/raters/registration
      - /v1/raters/me
      - /v1/raters/{externalSystem}/{externalId}
      - /v1/datasets/{datasetId}
      - /v1/datasets/{datasetId}/snippets
      - /v1/datasets/{datasetId}/prolific-completion
      - /v1/snippets/{snippetId}/rates
      - /v1/demographic-question-groups
      - /v1/demographic-questions
