management:
  endpoints:
    web:
      cors:
        max-age: 3600s
        allowed-methods: 'GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD'
        allowed-headers: '*'
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 1m
        enabled: false
