global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
#  - job_name: 'otel-collector'
#    static_configs:
#      - targets: ['otel-collector:8889']
  - job_name: 'code-annotation'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['code-annotation-server:8080']

rule_files:
  - 'alert-rules.yaml'

alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ['alertmanager:9093']