version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus:/etc/prometheus:ro
    ports:
      - '9090:9090'

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    restart: always
    ports:
      - '9093:9093'
    volumes:
      - ./alert-manager:/config
      - /mnt/secrets/slack_url:/config/slack_url
    command: --config.file=/config/alertmanager.yaml --log.level=debug

#  otel-collector:
#    image: otel/opentelemetry-collector-contrib:0.82.0
#    container_name: otel-collector
#    restart: always
#    command:
#      - --config=/etc/otelcol-contrib/config.yaml
#    volumes:
#      - ./otel/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
#    ports:
##      - '1888:1888' # pprof extension
##      - '8888:8888' # Prometheus metrics exposed by the Collector
#      - '8889:8889' # Prometheus exporter metrics
##      - '13133:13133' # health_check extension
##      - '4317:4317' # OTLP gRPC receiver
#      - '4318:4318' # OTLP http receiver
##      - '55679:55679' # zpages extension

networks:
  default:
    name: code-annotation